apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: amalkov-app
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: web-server
  template:
    metadata:
      labels:
        deployment: web-server
        app: amalkov-app
    spec:
      initContainers:
        - name: migration-container
          image: webimage
          envFrom:
            - secretRef:
                name: app-secret
            - configMapRef:
                name: app-config
          command: ["python3", "/app/manage.py", "migrate"]
          ports:
            - containerPort: 8000
      containers:
        - name: web-container
          image: webimage
          envFrom:
            - secretRef:
                name: app-secret
            - configMapRef:
                name: app-config
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000