apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: webimage
    newName: sodx/sampleapp
    newTag: v1.2.0

resources:
  - deployment.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - service.yaml
  - secret.yaml
