apiVersion: v1
kind: Service
metadata:
  name: amalkov-devops-final-service
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: amalkov-devops-final
  type: NodePort